module uim.exceptions.tests.exception;

